src/main/markdown/makinggwtbetter.md

Alas, the build jars still live in the old svn repo.
Currently, the instructions say to clone the gwt source twice instead...

Fix location of the gwt build tools

---

src/main/markdown/articles/mvp-architecture.md

Also added/updated links to EventBus and SimpleEventBus (com.google.web.bindery.shared versions)
Impetus of change was this PatchesWelcome issue https://code.google.com/p/google-web-toolkit/issues/detail?id=6231

Replace uses of HandlerManager with SimpleEventBus

---

src/main/markdown/doc/latest/tutorial/codeclient.md

DateTimeFormat.getMediumDateTimeFormat() is now deprecated.
It is recommended that DateTimeFormat.PredefinedFormat.DATE_TIME_MEDIUM is used in its place.

Remove deprecated  function call

---

src/main/markdown/articles/articles.md

URL of externally hosted article GWT Tutorial (written and contributed by me) is changed from http://codedrops.in/gwt-tutorial/ to http://www.codetab.org/gwt-tutorial/
Please update the changes in GWT Site.

URL of GWT Tutorial contributed by me is changed.

---

src/main/markdown/lifeofanissue.md

Change issue tracker links to target github.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/86)

Issues are moving to github

---

src/main/site/assets/less/layout.less

- Sometimes pegdown encloses first description in &lt;p>, setting display
inline so as there is no line breaks.
- Numbered lines font should be monospaced so as the pipe separator
is always in the same position.
- Space between &lt;li> was very small if last element is not a &lt;p>.
- Reduce font of italic to diferentiate.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/92)

Some css fixes in lists.

---

src/main/markdown/gettingstarted.md

Looks like the link to documentation on the `webAppCreator` class [on the Getting Started page](http://www.gwtproject.org/gettingstarted.html) is not entirely correct and the raw markdown is being displayed instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/87)

Fixed broken link on webAppCreator

---

src/main/markdown/doc/latest/DevGuideUiBinderI18n.md

gwtproject/gwt#9154
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/106)

Replace deprecated PropertiesFormat with new PropertyCatalogFactory in UiBinder I18N example

---

src/main/markdown/doc/latest/DevGuideA11y.md

codetalks.org does not contain any information about ARIA and it is not worth mentioning in article about a11y. This is the same pull request as #107 but is created from separate branch (not master).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/108)

Removed codetalks.org as source of information about ARIA as it does not contain it

---

src/main/site/assets/less/layout.less
src/main/site/assets/less/normalize.less

Breaking code makes code look unformated, it is better
to maintain the original author's format and let the user
scroll to vew full code.
Also better selection of fonts because in android code
was not shown with monospaced fonts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/103)

Don not break code lines, use scrolling instead.

---

src/main/markdown/articles/using_gwt_with_hibernate.md
src/main/markdown/doc/latest/DevGuideClientBundle.md
src/main/markdown/doc/latest/DevGuideServerCommunication.md
src/main/markdown/doc/latest/DevGuideUiBinder.md
src/main/markdown/doc/latest/DevGuideUiBinderI18n.md

a couple of links were showing as `[example](example.org)` instead of [`example`](example.org)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/112)

Fix broken links

---

src/main/resources/main.tpl

This reverts commit 25233ca5df1d35fbf579688fbdc164d1d0dc4131.
That commit caused [issue #79](https://github.com/gwtproject/gwt-site/issues/79). Maybe there is a way to achieve the desired behaviour without disrupting the workflow of (potential) contributors to the documentation?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/111)

Revert "Hide the main div while loading"

---

src/main/markdown/articles/mvp-architecture.md

somehow the `![screenshot]` command is ignored and directly rendered as HTML when surrounded by a `div`:
```
<div class="screenshot">
</div>
```
Other usages of the `![screenshot]` command are not surrounded by a `div`, so I removed the `div`.
Tested this locally and the images are now rendered as images.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/119)

fixing ![screenshot] images

---

src/main/markdown/doc/latest/DevGuideCompilingAndDebugging.md
src/main/markdown/doc/latest/FAQ_Server.md

I think the first link did not work because auf the special character '?' and the second link had a typo. 
I  tested both links locally. They now work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/128)

Fix 2 links in DevGuideCompilingAndDebugging.md

---

src/main/markdown/release-notes.md

Also removed multiple trailing whitespaces.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/147)

Fix typo in 2.8.0 (Beta1) release note

---

src/main/markdown/doc/latest/DevGuideSecuritySafeHtml.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/139)

Added missing whitespaces in markdown code of DevGuideSecuritySafeHtml

---

src/main/markdown/doc/latest/polymer-tutorial/elements-buildui.md

by adding "item-icon" it specifies, that the icon is used inside the paper-item. that allows for example the expected correct side alignment of the icons, which still works if a description(for example "Clear All") is longer.
example of how it should look like: http://s18.postimg.org/wy5s2vot5/gwtpoly.png
check out the polymer elements side for reference:
https://github.com/PolymerElements/paper-item/blob/master/demo/index.html#L102
https://elements.polymer-project.org/elements/paper-item?view=demo:demo/index.html&active=paper-item
so this:
<paper-icon-item role="listitem" class="x-scope paper-icon-item-0">
<div class="content-icon layout horizontal center style-scope paper-icon-item" id="contentIcon">
</div>
<iron-icon class="x-scope iron-icon-0">...</iron-icon> 
<div>Clear All</div> …

correct usage of paper-icon-item

---

src/main/markdown/doc/latest/polymer-tutorial/widgets-applogic.md

Current version has mismatch between the Java and XML files for naming the PaperCheckBox. Java field is named "done", XML names it "check". This causes compile error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/159)

Update PaperCheckBox field name to match Java

---

src/main/markdown/doc/latest/tutorial/create.md

When using a newer version of the chrome browser use 'Run as Web Application (GWT Super Dev Mode)' instead. The 'Google Web Toolkit Developer Plugin' needed for the default run mode doesen't work anymore with newer browsers
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/160)

gwt developer plugin doesn't work with newer chrome

---

src/main/markdown/articles/superdevmode.md

Update issue link for https "is not supported" to point to github link and use github issue #.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/172)

Fix https issue link

---

src/main/markdown/articles/gss_migration.md

These two snippets are already surrounded with "```" and should not be
indented 4 spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/175)

Fix extra indentation of code snippets in GSS Migration Guide

---

src/main/markdown/community.md
src/main/markdown/developer_spotlight.md
src/main/markdown/examples.md
src/main/markdown/gettingstarted.md
src/main/markdown/makinggwtbetter.md

- Remove link to "GWT Gallery" (app is down or not maintained anymore)
- Replace all links to "google code" with link to github
- Fix typo in makingwgtbetter.md
- Update gettingstarted.md (Super Dev Mode is default, plugin usage is deprecated)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/184)

Cleanup outdated information

---

src/main/markdown/doc/latest/polymer-tutorial/create.md

The new created project from webAppCreator uses the Maven Plugin for GWT there is no gwt:run goal, now we must use gwt:devmode, like says here https://tbroyer.github.io/gwt-maven-plugin/migrating.html
Sorry if my english is not accurate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/195)

Update to create.md

---

src/main/markdown/doc/latest/FAQ_GettingStarted.md
src/main/markdown/doc/latest/polymer-tutorial/elements-buildui.md
src/main/markdown/doc/latest/polymer-tutorial/widgets-buildui.md
src/main/markdown/doc/latest/tutorial/appengine.md
src/main/markdown/doc/latest/tutorial/index.md
src/main/markdown/gettingstarted.md

- Change "Google Web Toolkit" to "GWT"
- Change old "Sun"  URI to new "Oracle" Java SE download URI
- Change old appengine URIs to new google cloud URI scheme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/188)

"GWT naming" & URI cleanup

---

src/main/markdown/articles/articles.md
src/main/markdown/articles/config.xml
src/main/resources/toc.md

The GSS Migration Guide was only ever linked from the release notes
for 2.8.0 Beta 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/209)

Link gss_migration from the TOC and the articles landing page

---

src/main/site/missing-plugin/index.html

DevMode no longer works on Chrome, whichever the platform; and never worked in Edge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/217)

Update missing-plugin for Edge, and Chrome on all platforms

---

src/main/markdown/doc/latest/DevGuideTesting.md

Because the google events page throws a 404, I have updated the docs with a direct link to the video on YouTube
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/216)

Changed link to best practices talk to YouTube link

---

src/main/markdown/doc/latest/DevGuideTesting.md

In GWT 2.8, JUnitShell now defaults to running tests in prod mode, and you have to
pass a -devMode argument to get back the legacy development mode behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/198)

Update documentation wrt devmode vs prod for tests

---

src/main/site/index.html

Apparently, this is the only file and the only control char
(I'd blame console editing and doing Ctrl+V Ctrl+C)
Fixes #224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/225)

Remove ^C control chars from index.html

---

src/main/markdown/versions.md

Exchanged bad links with working ones from Google's code archive for releases of previous versions of GWT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/205)

* exchanged bad links for previous versions of GWT

---

README.md
src/main/markdown/articles/articles.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/231)

Fix broken headings in Markdown files

---

src/main/markdown/doc/latest/DevGuideUiPanels.md

…instead of UiObject.setVisible on the Layout wrapper element
returned by LayoutPanel#getWidgetContainerElement.
Fixes gwtproject/gwt#7544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/227)

Recommend LayoutPanel#setWidgetVisible to hide widgets

---

src/main/markdown/doc/latest/tutorial/debug.md

Eclipse only switches to the Debug perspective once the code reaches the breakpoint.
Fixes gwtproject/gwt#8439
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/226)

Fix list formatting + move sentence

---

src/main/markdown/doc/latest/DevGuideUiCustomCells.md

This page:
http://www.gwtproject.org/doc/latest/DevGuideUiCustomCells.html
says
"The core method that all Cells must implement is the [Cell#render(Context, C value, SafeHtmlBuilder)](/javadoc/latest/com/google/gwt/cell/client/Cell.html#render(com.google.gwt.cell.client.Cell.Context, C, com.google.gwt.safehtml.shared.SafeHtmlBuilder)) method, which ..."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/244)

Fix broken link in public documentation DevGuideUiCustomCells.html

---

src/main/markdown/makinggwtbetter.md

The build and run instructions on the github readme.md are more up to date than the webpage. To avoid redundant descriptions and easier maintainance simply link to the building and run section of the readme.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/228)

Reference to build and run instructions

---

src/main/markdown/doc/latest/DevGuideOrganizingProjects.md

Explicitly state that this is only one possibility and load ordering can vary.
Use .cache.js rather than .cache.html now that xsiframe is the default linker (been for a while actualy)
Fixes gwtproject/gwt#9188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/256)

Update bootstrapping example to (hopefully) disambiguate it

---

src/main/markdown/doc/latest/tutorial/JSON.md
src/main/markdown/doc/latest/tutorial/JUnit.md
src/main/markdown/doc/latest/tutorial/RPC.md
src/main/markdown/doc/latest/tutorial/Xsite.md
src/main/markdown/doc/latest/tutorial/buildui.md
src/main/markdown/doc/latest/tutorial/debug.md
src/main/markdown/doc/latest/tutorial/i18n.md

Hi GWT team,
Here's a trivial fix for code formatting and spelling errors found in [GWT Tutorials](http://www.gwtproject.org/doc/latest/tutorial/index.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/269)

Fix code format and spelling errors in tutorial

---

src/main/markdown/doc/latest/DevGuideTestingHtmlUnit.md

See https://github.com/gwtproject/gwt/blob/2.8.2/user/src/com/google/gwt/junit/RunStyleHtmlUnit.java#L286-L293, https://github.com/gwtproject/gwt/blob/2.8.2/user/src/com/google/gwt/junit/RunStyleHtmlUnit.java#L328-L329, and https://sourceforge.net/p/htmlunit/code/HEAD/tree/tags/HtmlUnit-2.19/src/main/java/com/gargoylesoftware/htmlunit/BrowserVersion.java#l122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/272)

Update RunStyle HtmlUnit supported browser emulations

---

src/main/markdown/download.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/274)

Fix broken link to GWT Eclipse Plugin Logo

---

pom.xml

Seems that Grunt doesn't work anymore with the old node and npm versions. This PR fixes that issue by updating deps:
- update frontend-maven-plugin
- update node and npm version

Update deps to fix build

---

README.md
pom.xml

Using the Jetty plugin facilitates running the site and testing of local changes. This makes contributing easier.

Reintroduce jetty plugin for running and testing the site

---

src/main/markdown/community.md
src/main/markdown/doc/latest/FAQ.md
src/main/resources/main.tpl
src/main/site/images/gitter-logo.svg
src/main/site/index.html

This pull request replaces several stale G+ links with links to the very active Gitter community ( resolves #288 ).

Replace Google+ community links with links to Gitter community

---

src/main/site/assets/less/style.less

Updated fixes based off the discussion in #290 
Fixes a small portion of the Creative Commons text overflowing the sidebar on displays >= 960px wide.

Fix creative commons showing on collapsed sidebar

---

src/main/markdown/steering.md

as per https://groups.google.com/d/msgid/gwt-steering/CAN4j5mtaztSu1ANOZpsEVW%3DMYndR-bo6dAB5sLWML7rC1_QWng%40mail.gmail.com

Remove Christian Goudreau from SC members list.

---

src/main/markdown/articles/superdevmode.md
src/main/markdown/doc/latest/DevGuideCompilingAndDebugging.md

Mention more recent Java versions supported by the GWT compiler.
Found the values here: https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/util/arg/SourceLevel.java

Update command line options for Compiler, DevMode and SuperDevMode

---

src/main/markdown/articles/superdevmode.md
src/main/markdown/doc/latest/DevGuideCompilingAndDebugging.md
src/main/markdown/download.md
src/main/markdown/gettingstarted.md
src/main/markdown/overview.md
src/main/markdown/release-notes.md
src/main/markdown/versions.md

Changes to generated docs (javadoc, emulation summary) will follow, since that is a huge change and can't be manually reviewed like this can.

Update site (except generated docs) for GWT 2.10.0 release

---

src/main/resources/main.tpl
src/main/site/index.html

It is unclear who has access to the account (wasn't handled over with other resources), is unnecessary, and may not be legal.
Fixes #311

Remove Google Analytics

---

src/main/markdown/versions.md

Also, remove old deprecated link shortener.
Fixes #340

Use https to download GWT releases

---

src/main/markdown/config.xml
src/main/markdown/roadmap.md
src/main/site/assets/build/fonts/icons/icons.css
src/main/site/index.html

A roadmap provides confidence for customers of the GWT SDK.

add a roadmap site

---

src/main/markdown/makinggwtbetter.md

Gerrit is no longer part of the workflow and AFAIK the CLA requirement was also removed.
Closes #252

Remove notes about Gerrit and CLA

---

src/main/site/index.html

Switch to show new gettingstarted-v2.md in the main menu.  Ie: Here:
_Note:_  To test this change, I had to add:
```
set JDK_JAVA_OPTIONS=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED
```
before running `mvn clean install`, otherwise I gor the error:
```
java.lang.RuntimeException: Error creating extended parser class: Could not determine whether class 'org.pegdown.Parser$$parboiled' has already been loaded
```
Probably because I'm running Java 17.

Switch to show new gettingstarted-v2.md by default.

---

src/main/markdown/doc/latest/DevGuideCodingBasicsJsInterop.md

Hi :).
It would be nice to mention the `-generateJsInteropExports` option within the `DevGuideCodingBasicsJsInterop` (JS interop) page.
Have spent quite long time to figure why the JS didn't get Java stuff exported according to documetation. 
I beleive this information absence can prevent many developers from using this great feature.
Please feel free to decline, but consider to mention that information within the page the way you are fine with it.
Thank you.

Mention of "generateJsInteropExports" option within the JsInterop page

---

src/main/markdown/release-notes.md

In the past, release notes files were created per-release, but those have all been deleted - the earliest such release was 2.5, old enough that I didn't feel it was necessary to dig through history and find those notes and restore them, but just deleted the broken links.
Old javadoc links apparently used `.` instead of `/` delimiters for packages, and left off `.html` suffixes. In theory our server will automatically deal with the missing suffixes, but won't rewrite paths.
Going back to 1.x days, some documentation was written by adding inner classes to a DeveloperGuide class, and adding notes there. I've found the present-day equivelents of each of those old documents, or just deleted the links where nothing seemed appropriate.

Fix or remove broken links in release-notes.md

---

src/main/markdown/community-group-charter.md
src/main/markdown/doc/latest/polymer-tutorial/create.md
src/main/markdown/doc/latest/polymer-tutorial/elements-buildui.md
src/main/markdown/doc/latest/polymer-tutorial/widgets-buildui.md
src/main/markdown/doc/latest/tutorial/index.md
src/main/markdown/download.md
src/main/markdown/gettingstarted-v2.md
src/main/markdown/gettingstarted.md

Does not fix release notes, javadocs, nor any external links.

Fix broken links to other markdown pages

---

.github/workflows/build.yml

CI doesn't allow v3 to run any longer, so site deployments are disabled without this.

Update to actions/upload-artifact@v4

---

src/main/site/doctype/2.12.2/gwt-module.dtd

It's just a copy of 2.12.1 version since nothing changed

Add DTD for 2.12.2
