src/main/markdown/steering.md

Added Justin Hickman and modified Colin's Biz

Updated Steering Committee 

---

src/main/markdown/doc/latest/tutorial/RPC.md

Bug: issue [#9096](https://code.google.com/p/google-web-toolkit/issues/detail?id=9096)

Fix bad conversion of RPC.md

---

src/main/resources/main.tpl
src/main/site/index.html

Fix typo, add links

---

src/main/markdown/doc/latest/tutorial/codeclient.md

I edited  the line where a new ArrayList is created

edited the create new Arraylist

---

src/main/markdown/doc/latest/tutorial/codeclient.md

Using the same comment as it was before.

changing comment

---

src/main/markdown/index.md

Change the sentence "how you can quickly develop performance AJAX applications" to "how you can quickly develop high-performance AJAX applications".

Change performance to high-performance in index.md

---

src/main/markdown/doc/latest/tutorial/codeclient.md

Sorry about the big pull request. The markdown numbering is all screwed up because of some white space issues.
I also removed a random div element from the code and added some asterisks to a couple of items.

Fix formatting of markdown.

---

src/main/markdown/doc/latest/DevGuideUiEditors.md

Sorry if this is unwanted noise but I noticed a formatting glitch on the site.

Fix formatting in DevGuideUiEditors.md

---

src/main/markdown/GWTPolicy.md

+ add link to folder containing all version of the logo

Add link to graphical guidelines document

---

src/main/markdown/doc/latest/tutorial/style.md

* Properly indent code blocks inside lists to not break numbering
* Properly indent code inside code blocks
* Syntax-highlight code blocks
* replaced `<span class="strike">` with a Java comment to denote that the line has been deleted (as explained in prose just above the code block)
* remove some old cruft in the HTML host page: transitional doctype, type and language attributes on script element, and the history iframe.

Fix formatting

---

src/main/markdown/articles/mvp-architecture-2.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/82)

Fixed shouldFirdClickEvent() type.

---

src/main/markdown/doc/latest/tutorial/RPC.md

Corrected errors in some lists formatting.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/84)

Fix markdown syntax : Tutorial - Using GWT RPC

---

src/main/markdown/community-group-charter.md
src/main/markdown/doc/latest/FAQ_GettingStarted.md
src/main/markdown/makinggwtbetter.md
src/main/markdown/release-notes.md

Make sure all links to the issue tracker now point to GitHub.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/89)

Issues have moved to GitHub

---

src/main/markdown/lifeofanissue.md

Note: this is part of a proposal for managing issues on GitHub. Please do not merge until we discussed that proposal with the Steering Committee.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/90)

Updated "life of an issue" for GitHub issues

---

src/main/markdown/learnmore-sdk.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/93)

Correct typo - "Simple" to "Simply"

---

src/main/markdown/doc/latest/DevGuideI18nConstants.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/77)

Fix broken markdown on I18n constant dev guive

---

src/main/markdown/doc/latest/DevGuideMvpActivitiesAndPlaces.md

Replaced non-existent Google I/O links with YouTube valid ones.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/97)

Updated "Related resources" video links

---

src/main/markdown/doc/latest/polymer-tutorial/introduction.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/98)

Restore removed screenshots by mistake

---

src/main/markdown/doc/latest/DevGuideI18n.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/104)

Convert html to markdown. Remove obsolete stuff

---

src/main/markdown/doc/latest/tutorial/manageevents.md
src/main/markdown/doc/latest/tutorial/style.md

Fixing indentation of code blocks so that the numbered lists in which they appear are numbered correctly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/102)

Fixing misnumbered list items caused by inconsistent indentation

---

src/main/markdown/doc/latest/DevGuideCodingBasics.md
src/main/markdown/doc/latest/DevGuideServerCommunication.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/109)

Coding Basics section. Fixed some misprints

---

src/main/markdown/makinggwtbetter.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/110)

Use markdown for tables in makinggwtbetter.md

---

src/main/markdown/makinggwtbetter.md

Two words were accidentally reversed in a sentence. (Sorry Yoda!)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/123)

Fixed a grammar mistake in makinggwtbetter.md

---

src/main/markdown/doc/latest/tutorial/manageevents.md

Maybe this is a typo in this regular expression.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/126)

Replace "&#92;&#92;" by "\\"

---

src/main/markdown/doc/latest/DevGuideCodeSplitting.md

These tags do not highlight text portions inside the code paragraph, but written as plain html-tag. This maybe is irritating newbies.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/125)

Removed <strong>-tags in code paragraphs.

---

src/main/markdown/makinggwtbetter.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/130)

Update makinggwtbetter.md to reflect migration of tools repo to Github

---

src/main/markdown/doc/latest/polymer-tutorial/introduction.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/133)

Added correct link to correct project page.

---

src/main/site/assets/less/print.less

before | after
------------ | -------------
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/140)

Fixed unordered list markers in print version.

---

src/main/markdown/release-notes.md

work in progress
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/137)

Start release note for GWT 2.8

---

src/main/markdown/articles/gss_migration.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/141)

Add a migration guide for gss

---

src/main/markdown/release-notes.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/142)

Remove unused sections

---

src/main/markdown/articles/gss_migration.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/143)

Remove strong in code sample

---

src/main/markdown/articles/gss_migration.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/144)

Fix formatting issue

---

src/main/markdown/doc/latest/tutorial/index.md

Changed wit-> with
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/148)

Update index.md to correct a typo

---

src/main/markdown/doc/latest/polymer-tutorial/elements-applogic.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/131)

Update elements-applogic.md by including a note for step 1

---

src/main/markdown/release-notes.md

Fixes #145
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/146)

Fix release notes bugs

---

src/main/markdown/release-notes.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/154)

Fix one more typo in 2.8.0 (Beta1) release note

---

src/main/markdown/download.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/152)

Flat red buttons to match the site with hover effect

---

pom.xml
src/main/site/doctype/2.8.0/gwt-module.dtd

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/155)

Adding 2.8.0 gwt-module.dtd doctype.

---

src/main/markdown/doc/latest/DevGuideAutoBeans.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/162)

Add missing 'inherit'

---

src/main/markdown/doc/latest/polymer-tutorial/widgets-applogic.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/161)

Add missing .dialog style class.

---

src/main/markdown/articles/superdevmode.md

- Update CodeServer output
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/153)

Revise Super Dev Mode article for 2.8

---

src/main/markdown/articles/dom_events_memory_leaks_and_you.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/166)

Corrected a referenced link

---

src/main/markdown/doc/latest/DevGuideUiBinder.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/171)

Make effectively final fields final

---

src/main/markdown/articles/using_gwt_with_hibernate.md

Merely fixing a typo in code block.
(My apology if this is not how it's done properly.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/178)

Fixed typo in [Resources -> GWT & Hibernate]

---

src/main/markdown/release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/181)

Prepare release note for GWT 2.8RC1

---

src/main/markdown/download.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/185)

Modify download link to GWT 2.8 RC-1

---

src/main/markdown/doc/latest/tutorial/buildui.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/134)

Fix for grammar in buildui.md

---

src/main/markdown/download.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/186)

Use shortened url for download link

---

src/main/markdown/download.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/199)

Update download link to 2.8.0-rc3

---

src/main/markdown/download.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/204)

Update download URL

---

src/main/markdown/release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/203)

Update Release notes for GWT2.8 RC3 and final release

---

src/main/markdown/versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/207)

Update version page: add GWT 2.8 release

---

src/main/markdown/overview.md

Update 'what's new' section on Overview page with link to the latest GWT release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/206)

Update 'what's new' link on Overview page

---

src/main/markdown/download.md

@branflake2267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/218)

point to GWT Eclipse plugin instead of GPE

---

README.md
package.json
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/223)

Fix compilation problems by upgrading versions

---

src/main/markdown/release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/232)

Update release notes for GWT 2.8.1

---

src/main/markdown/steering.md

Removed company from Justin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/235)

Update to steering.md

---

src/main/markdown/meetingnotes.md
src/main/resources/toc.md

Add steering committee meeting notes from 2015 - 2016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/173)

Add steering committee meeting notes

---

src/main/markdown/doc/latest/DevGuideA11y.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/237)

Fix typo. diabled -> disabled

---

src/main/site/doctype/2.8.1/gwt-module.dtd

I copy-pasted the 2.8.0 dtd.
See https://github.com/vaadin/maven-plugin/pull/100#issuecomment-303312849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/240)

Adding missing DTD for GWT 2.8.1

---

src/main/markdown/doc/latest/DevGuideUiCellWidgets.md

Fixed typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/243)

Fixed broken url format due to newline

---

src/main/markdown/doc/latest/DevGuideUiEditors.md

Fixed typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/242)

Fixed typo

---

src/main/markdown/steering.md

Replace @cromwellian with Bhaskar (no GitHub handle?), update @stephenh's affiliation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/239)

Update list of steering committee members

---

src/main/markdown/doc/latest/tutorial/i18n.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/245)

Fix gwtproject/gwt-site#177

---

src/main/markdown/articles/mvp-architecture-2.md
src/main/markdown/articles/mvp-architecture.md
src/main/markdown/doc/latest/DevGuideMvpActivitiesAndPlaces.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/247)

Fix gwtproject/gwt-site#170

---

src/main/markdown/doc/latest/DevGuideCompilingAndDebugging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/255)

Fix DevMode class name typo.

---

src/main/markdown/download.md
src/main/markdown/gettingstarted.md
src/main/markdown/release-notes.md
src/main/markdown/versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/260)

Update release notes for 2.8.2 release

---

src/main/markdown/doc/latest/DevGuideCodingBasicsJSNI.md

A possible solution for #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/259)

Added info to use jsinterop instead of jsni

---

src/main/site/doctype/2.8.2/gwt-module.dtd

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/264)

Copy 2.8.1 dtd to 2.8.2 version path

---

src/main/markdown/makinggwtbetter.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/267)

Fix JUnit with Ant broken link

---

src/main/markdown/doc/latest/DevGuideCodingBasicsJsInterop.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/273)

unordered list is not showing properly on website

---

src/main/markdown/doc/latest/DevGuideOrganizingProjects.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/275)

Corrected a grammar mistake.

---

src/main/markdown/doc/latest/DevGuideUiBrowser.md

It's been a long time since I've heard it called DHTML ;-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/283)

Change 'DHTML' to just 'HTML'

---

src/main/markdown/doc/latest/DevGuideI18nLocale.md

links
https://github.com/gwtproject/gwt/issues/5768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gwtproject/gwt-site/278)

reference open issue for default locale

---

src/main/markdown/doc/latest/DevGuideCodingBasicsCompatibility.md

The previous text talked about GWT 1.5 and GWT 2.0 and Java 1.5 etc.

Update Java version in "Language Support" section

---

src/main/site/doctype/2.10.0/gwt-module.dtd

Fixes gwt issue gwtproject/gwt#9770
Checked out the release/2.10 branch and copied the `gwt-module.dtd` here.  Doesn't appear to be any changes since 2.9.0

Added gwt-module.dtd for version 2.10.0

---

src/main/markdown/versions.md

Fixed the year for the builds 2.11.0 and 2.10.1

Fix website version dates

---

src/main/markdown/versions.md

The url for download is wrong. I fixed it. :)

Fix 2.11.0 download

---

src/main/markdown/versions.md

Versions page: fix links and swap columns

---

src/main/markdown/articles/testing_methodologies_using_gwt.md
src/main/markdown/doc/latest/DevGuideCodingBasicsDelayed.md
src/main/markdown/doc/latest/DevGuideCodingBasicsFormatting.md
src/main/markdown/doc/latest/DevGuideCodingBasicsJSNI.md
src/main/markdown/doc/latest/DevGuideCodingBasicsJsInterop.md
src/main/markdown/doc/latest/DevGuideI18nMessages.md
src/main/markdown/doc/latest/DevGuideTesting.md
src/main/markdown/doc/latest/DevGuideTestingCoverage.md

Replacement for #271 (merged master into the branch).

Dev guide code style
